### PR TITLE
Line Number improvements

### PR DESCRIPTION
**Pull request by not-nef**
@Moosems Your thing aint workin or i set it up wrong

### CODE REVIEW

**Comment by Moosems** [comment]
That's on your end. It works

**Comment by not-nef** [comment]
You sure? Did you try my code? Maybe i set it up wrong

**Comment by Moosems** [comment]
It's working for me. What do you mean it isn't working??

**Comment by not-nef** [comment]
> It's working for me. What do you mean it isn't working??

image

**Comment by not-nef** [comment]
See? It aint workin ( latest commit )

**Comment by Moosems** [comment]
That's weird. Looks fine on my computer

**Comment by Moosems** [comment]
Screen Shot 2022-09-28 at 12 34 05 PM

**Comment by Moosems** [comment]
@not-nef With the linenums that's cause you copy pasted and the binds need to be set up for that. That's not the fault of tklinenums. Like I keep saying to fix this just use CodeView from chlorophyll. As for the sticking out a lot can you please create a minimum reproducible example piece of code so I can debug and create a release with a fix or find the error that you might have made?

**Comment by not-nef** [comment]
Does it update? And did you try disableing the syntax highlighting?

**Comment by Moosems** [comment]
??

**Comment by not-nef** [comment]
@Moosems i added a test.py in the project root which is the thing you wanted. Linenumbers dont update

**Comment by not-nef** [comment]
Ah shit forgot to push

**Comment by not-nef** [comment]
There you go

**Comment by Moosems** [comment]
No need for language

**Comment by Moosems** [comment]
@not-nef Can you give an image with the Minimum Reproducible Example? It only gives the effect if I make it spread out sideways. If that's the effect you want that's not the fault of of tklinenums but rather improper packing

**Comment by not-nef** [comment]
Thats not what im talking about. The line numbers simple dont work

**Comment by Moosems** [comment]
@not-nef That's not the linenumbers. Here's a fix to the example:

```python

from tkinter import Tk, Text, Frame
from tkinter import ttk
from tkinter.font import Font
from tklinenums import TkLineNumbers

root = Tk()

main_frame = Frame(root)
main_frame.pack(fill="both", expand=True)

textwidget = Text(main_frame, width=100, borderwidth=0, height=root.winfo_height() - 125)
textwidget.text = textwidget
textwidget.grid(row=0, column=1, sticky="nsew")

style = ttk.Style()
style.configure("TLineNumbers", background="#ffffff", foreground="#2197db")

font = Font(family="Courier New bold", size=15, name="TkLineNumsFont")

linenums = TkLineNumbers(main_frame, textwidget, font)
linenums.grid(row=0, column=0, sticky="nsew")
linenums.reload(font)

textwidget.bind("<<ContentChanged>>", lambda event: root.after_idle(linenums.redraw()))
textwidget["yscrollcommand"] = linenums.redraw()

root.mainloop()
```

**Comment by Moosems** [comment]
> Thats not what im talking about. The line numbers simply dont work

You mean not updating when typing? That's not the linenumbers, that's bad binding. Please stop blaming the code the binds needed are as shown below:

```python
textwidget.bind("<Key>", lambda event: root.after_idle(linenums.redraw))
textwidget.bind("<ButtonRelease-1>", lambda event: root.after_idle(linenums.redraw))
```

**Comment by not-nef** [comment]
What do you mean thats not the linenumbers? Why is it not working then?

**Comment by not-nef** [comment]
I always told you i probably set it up wrong thats why i asked you for help!! I never expected the code to be buggy i know you can do this type of stuff i just asked you how to properely set it up. Sorry if that wasnt clear

**Comment by Moosems** [comment]
No worries :)

**Comment by not-nef** [comment]
This is with the bindings you sent

image

**Comment by Moosems** [comment]
@not-nef Here are the bindings to use:
```python
from platform import system

if system() == "Darwin":
    contmand = "Command"
else:
    contmand = "Control"
text.bind("<Key>", lambda event: root.after_idle(linenums.redraw), add=True)
text.bind(f"<BackSpace>", lambda event: root.after_idle(linenums.redraw), add=True)
text.bind(f"<{contmand}-v>", lambda event: root.after_idle(linenums.redraw), add=True)
text["yscrollcommand"] = linenums.redraw
```

This works perfectly fine in a normal Text widget (see below) but doesn't seem to work in txt2. I'll leave it up to you to figure out the `"<Key>"` binding and why it's not working

Working:

```python
from tkinter import Text, Tk
from tkinter.font import Font
from tkinter.ttk import Style
from platform import system

if system() == "Darwin":
    contmand = "Command"
else:
    contmand = "Control"

from tklinenums import TkLineNumbers

root = Tk()

style = Style()
style.configure("TLineNumbers", background="#ffffff", foreground="#2197db")

text = Text(root, wrap="char")
text.pack(side="right")

for i in range(50):
    text.insert("end", f"Line {i+1}\n")

font = Font(family="Courier New bold", size=15, name="TkLineNumsFont")

linenums = TkLineNumbers(root, text, font)
linenums.pack(fill="y", side="left", expand=True)
linenums.reload(font)

text.bind("<Key>", lambda event: root.after_idle(linenums.redraw), add=True)
text.bind(f"<BackSpace>", lambda event: root.after_idle(linenums.redraw), add=True)
text.bind(f"<{contmand}-v>", lambda event: root.after_idle(linenums.redraw), add=True)
text["yscrollcommand"] = linenums.redraw

root.mainloop()
```

**Comment by not-nef** [comment]
I have an idea. To use tkdnd you have to make the main window a tkdnd.Tk widget. Maybe it doesnt pass the after_idle call to the tk widget behind it. What do you think?

**Comment by not-nef** [comment]
Can confirm its not because of tkdnd

**Comment by not-nef** [comment]
image

**Comment by not-nef** [comment]
image

**Comment by HuyHung1408** [comment]
yeah it's **looks** a bit misalign, I would prefer the numbers to be right align

**Comment by Moosems** [comment]
Fixed in pypi release 1.5

**Pull request merged**
