### PR TITLE
Syntax highlighting

### PR DESCRIPTION
**Pull request by not-nef**
FUCK YES

### CODE REVIEW

**Comment by not-nef** [comment]
@Moosems could you do some bug finding when you have time? Would be epic!

**Comment by sumeshir26** [comment]
What happened to line numbers?

**Comment by sumeshir26** [comment]
and you revealed your name by showing your private path

**Comment by not-nef** [comment]
> What happened to line numbers?

Nothing?

**Comment by not-nef** [comment]
> and you revealed your name by showing your private path

Oh fuck

**Comment by Moosems** [comment]
> @Moosems could you do some bug finding when you have time? Would be epic!

I'll do my best. I'm gonna be really busy this morning but I might have time later!

**Comment by Moosems** [comment]
So how exactly does the highlighting work? I'm not getting any color for a python file...

**Comment by im-coder-lg** [comment]
whyd you have to swear bruh

**Comment by Moosems** [comment]
That's what I was thinking but didn't want to say anything

**Comment by sumeshir26** [comment]
@Moosems theres a setting to enablr code editing

**Comment by Moosems** [comment]
@sumeshir26 I have it on right now :|

**Comment by not-nef** [comment]
@Moosems Restart the app after turning on the setting. Now the syntax should be highlighted (if you open a file or save it).

**Comment by Moosems** [comment]
@not-nef applysettings() doesn't work if it is on for some reason

**Comment by not-nef** [comment]
What? That cant be!

**Comment by not-nef** [comment]
Are you sure? @Moosems

**Comment by Moosems** [comment]
Yeah. It doesn't load the app. It's so weird

**Comment by Moosems** [comment]
I just narrowed it down to line 60 in applysettings.py @not-nef `    tabmanager.buildtabs()`

**Comment by not-nef** [comment]
It loads the app completely fine for me. Maybe a mac issue?

**Comment by Moosems** [comment]
Possibly. It's real weird though

**Comment by Moosems** [comment]
@not-nef I found that it seems to be an issue with buildtabs(). will look into it further

**Comment by Moosems** [comment]
@not-nef I found the issue. change `button.update()` to button.update_idletasks()`

**Comment by Moosems** [comment]
in buildtabs()

**Pull request merged**
