### PR TITLE
Bigger README logo

### PR DESCRIPTION
**Pull request by EduardoJTR**

### CODE REVIEW

**Comment by not-nef** [comment]
Would you please make the background transparent, just like it is in the current logo? Thanks!

**Comment by not-nef** [comment]
Also i dont think that the huge logo fits that well

**Comment by EduardoJTR** [comment]
Bettter now?

**Comment by not-nef** [comment]
Yes

**Review by Moosems — CHANGES_REQUESTED** [review]
Nice logo. Needs to have a specific version for readme and app because the iconphoto now looks massive

**Comment by not-nef** [comment]
Huh? What do you mean?

**Comment by Moosems** [comment]
I would separate the readme and app logo sizes because the app uses the logo and if it's super big then it will take the max size available on the os

**Comment by not-nef** [comment]
Yea that would be good

**Pull request closed without merging**
