### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by not-nef**
I am inviting everyone to work with me on this.

### CODE REVIEW

**Comment by sumeshir26** [comment]
Nice :) Reviewing soon

**Review by sumeshir26 — CHANGES_REQUESTED** [review]
Hey this is not working:
image
It seems to not detect things in its own dir

**Comment by sumeshir26** [comment]
Well once i cd to the src dir it works... odd...

BTW the UI looks nice!

**Review by sumeshir26 — APPROVED** [review]

**Comment by not-nef** [comment]
@sumeshir26 i forgot that

**Comment by not-nef** [comment]
and thanks a lot btw!

**Comment by sumeshir26** [comment]
Np, I think the ui would look better if you remove the border around the frames, did u try that?

**Comment by not-nef** [comment]
i made the borders so you could differentiate between sidebar and settings page. feel free to change it but please dont completely remove it or find a way to make them differentiable

**Comment by sumeshir26** [comment]
Ok. do it how u feel is good

**Comment by sumeshir26** [comment]
@not-nef I added a font loading method which does not rely on `matplotlib` but on `Tkinter` only, and it dosent take forever to build the font cache

**Comment by im-coder-lg** [comment]
Hi guys, it's me. I am not officially back since my exams are coming(the first exams of the year), and I couldn't respond much since I had problems of my own, but hey, I am back to help whenever I can.
Git is version control, ie. it allows you to save revisions of a file through commits - a secure method to save a snapshot of your edits. Each commit is secured by its SHA256 hash, which we call a commit tag/commit hash/etc.

Git, in its entirety, is quite simple. Sure, you have to set user config, but I have an ace up my sleeve for that.

So, let's make a simple guide.

### Add/Stage files
Whenever you commit, you have to select the files you want to commit, ie. if you updated docs and are testing a file edit, you make sure that doesn't get staged(ready for committing) so that you can test peacefully without the pains of accusations(they do lead back to you). Git is a CLI, so we need to use commands. These are universal, so no changes will take place.
```shell
$ # To stage particular file(s)
$ git add filename.ext filename2.ext # and so on
```
| filename => file name
| ---


| ext=> file extension
| ---

### Commit

So, this is a bit easy. Committing is just taking a snapshot locally. We all know how to do it, so I'll just shoot.
```shell
# Commit
$ git commit -m "Title message: following semantic commits is better" -m "Description"
# You can sign them(flag: -S), but that is of no use; any way you will learn it and possibly regret it too - failed for me :/
```

### Push

This is fairly easy. This depends upon your file changes, so it is relative to the bits changed.

```
git push
```

# My ace.
GitHub CLI. It is a smart thing since it is an extension of Git. Once you install and type `gh auth login`, it asks for authenticating your Git credentials, so it's easy to set Git configuration. It's available for Windows, Mac and Linux, at [cli.github.com](https://cli.github.com).

Once you log in, you can clone repos like so:
```
gh repo clone [user-name]/[repo-name]
```
Please amend the user-name and repo-name values w/ your own ***WITHOUT*** the square brackets.

**Comment by im-coder-lg** [comment]
PS: Commit hashes are so random, it is SO rare to get the same hash; plus it's useless since that is a conflict.
PPS: You can use them to link back to commits here.

**Comment by sumeshir26** [comment]
@not-nef I mostly use VsCode's github intigration. Just click t icon on t sidebar

**Comment by not-nef** [comment]
Thanks!!

**Comment by not-nef** [comment]
First commit with git! finally

**Comment by not-nef** [comment]
programming is hard

**Comment by not-nef** [comment]
But settings do not take effect yet

**Comment by not-nef** [comment]
yay

**Comment by sumeshir26** [comment]
What about a font size option?

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
Best to use Git, if you want. That is helpful though. Did you setup Got credentials like I told you?

**Comment by not-nef** [comment]
I use vscodes git integration. When i did my first push, it asked me to sign in with github oauth and then it worked

**Comment by not-nef** [comment]
> What about a font size option?

Sure, why not.

How do you like the new UI?

**Comment by sumeshir26** [comment]
> > What about a font size option?
> 
> Sure, why not.
> 
> How do you like the new UI?

Looks nice, The background looks better than the border

**Comment by not-nef** [comment]
that took a bit

**Comment by not-nef** [comment]
Courier New turned out to not be the default font

**Comment by not-nef** [comment]
Gonna add font size, mica and hotkey setting tomorrow!

**Comment by sumeshir26** [comment]
@not-nef I added the font size option, do you think it is good?

(Also, you should _reallay_ get rid of `txt2.py` since it causes many problems like not cfgtools.init() not working when running it

**Comment by not-nef** [comment]
i was about to do commit that ._.

**Comment by not-nef** [comment]
btw your method of getting a list for the fonts does not have all fonts it seems

**Comment by not-nef** [comment]
this is a huge pr

**Comment by sumeshir26** [comment]
> btw your method of getting a list for the fonts does not have all fonts it seems

What fonts are not seen by upu?

**Comment by not-nef** [comment]
Helvetica eg

**Comment by not-nef** [comment]
do you see it in the dropdown?

**Comment by not-nef** [comment]
I think we are ready!

**Comment by HuyHung1408** [comment]
I think I've missed lots of things here 🥲, just checked it out, looks great tbh

**Comment by not-nef** [comment]
Thanks! :D

**Pull request merged**
