### PR TITLE
Markdown Preview

### PR DESCRIPTION
**Pull request by not-nef**

### CODE REVIEW

**Comment by not-nef** [comment]
Can someone pls help me find a way to increase the height of the html widget?

**Comment by Moosems** [comment]
I'll take a look sometime soon. Does the height value not work?

**Comment by not-nef** [comment]
Yea, the parameter does nothing. You can set the width with the place call, but not the height

**Comment by Moosems** [comment]
I can't close the preview...

**Comment by not-nef** [comment]
Yes thats missing

**Comment by not-nef** [comment]
This close button is only temporary, and will be replaced by a button in a dropdown when the new menu bar is done

**Pull request merged**
